### ISSUE TITLE
Failed to lookup view "error" in views directory

### ISSUE THREAD

**Issue by mchandleraz** [jillesme/node-upload#2]
When trying to run the project, I get:
`Error: Failed to lookup view "error" in views directory "/Users/mattchandler/Projects/node/node-upload/views"
   at EventEmitter.app.render (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/application.js:519:17)
   at ServerResponse.res.render (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/response.js:904:7)
   at /Users/mattchandler/Projects/node/node-upload/app.js:48:9
   at Layer.handle_error (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/layer.js:58:5)
   at trim_prefix (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/index.js:267:13)
   at /Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/index.js:236:9
   at Function.proto.process_params (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/index.js:311:12)
   at /Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/index.js:227:12
   at Function.match_layer (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/index.js:294:3)
   at IncomingMessage.next (/Users/mattchandler/Projects/node/node-upload/node_modules/express/lib/router/index.js:188:10)`

**Comment by jillesme** [comment]
Do a `git checkout 06ac62360c4b1447ad051154bdc3676c593dd00a` if you want, I was transitioning to handlebars from hogan but didn't have time to finish it. 

I still want to use handlebars rather than hjs.. If you check the latest commit it says "broke build". Should've used a separate branch but I didn't at the time
